---
- name: Create a template from qcow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: production
    template_name: centos7_template
    template_memory: 4GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: mydata

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ lookup('env','OVIRT_URL') }}"
        username: "{{ lookup('env','OVIRT_USERNAME') }}"
        password: "{{ lookup('env','OVIRT_PASSWORD') }}"
        insecure: true
      tags:
        - always

  roles:
    - ovirt-ansible-image-template 

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
