---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    db_vm:
      cluster: golden_env_mixed_1
      root_password: 123456
      domain: example.com
      memory: 4GiB
      cores: 2
      state: running

    httpd_vm:
      cluster: golden_env_mixed_1
      root_password: 123456
      domain: example.com
      memory: 2GiB
      cores: 2
      state: running
  
    affinity_groups:
      - name: db-ag
        cluster: production 
        vm_enforcing: true
        vm_rule: negative
        vms:
          - postgresql-vm-0
          - postgresql-vm-1

    vms:
      - name: apache-vm-1
        tag: httpd
        profile: "{{ httpd_vm }}"
      - name: apache-vm-2
        tag: httpd
        profile: "{{ httpd_vm }}"
        state: stopped
      - name: postgresql-vm
        tag: db
        profile: "{{ db_vm }}"

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ lookup('env','OVIRT_URL') }}"
        username: "{{ lookup('env','OVIRT_USERNAME') }}"
        password: "{{ lookup('env','OVIRT_PASSWORD') }}"
        ca_file: "{{ lookup('env','OVIRT_CAFILE') }}"
        insecure: true
              #      environment:
              #        OVIRT_URL: "{{ url }}"
              #        OVIRT_USERNAME: "{{ username }}"
              #        OVIRT_PASSWORD: "{{ password }}"
              #        insecure: true
      tags:
        - always

  roles:
    - oVirt.vm-infra

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

