---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    db_vm:
      cluster: golden_env_mixed_1
      root_password: 123456
      domain: example.com
      memory: 4GiB
      cores: 2
      state: running

    httpd_vm:
      cluster: golden_env_mixed_1
      root_password: 123456
      domain: example.com
      memory: 2GiB
      cores: 2
      state: running
  
    affinity_groups:
      - name: db-ag
        cluster: production 
        vm_enforcing: true
        vm_rule: negative
        vms:
          - postgresql-vm-0
          - postgresql-vm-1

    vms:
      - name: apache-vm-1
        tag: httpd
        profile: "{{ httpd_vm }}"
      - name: apache-vm-2
        tag: httpd
        profile: "{{ httpd_vm }}"
        state: stopped
      - name: postgresql-vm
        tag: db
        profile: "{{ db_vm }}"

  roles:
    - oVirt.vm-infra
